[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
ENVIRONMENT = "production"
PYTHONPATH = "/app/backend"
