[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production.variables]
ENVIRONMENT = "production"
PYTHONPATH = "/app/backend"
