services:
  - type: web
    name: inmatch-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: "/health"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /app
      - key: CORS_ORIGINS
        value: https://in-match-pro.vercel.app
    
  - type: static
    name: inmatch-frontend
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com
      - key: VITE_ENVIRONMENT
        value: production
    routes:
      - type: rewrite
        source: "/api/*"
        destination: "https://your-backend-url.onrender.com/api/*"
      - type: rewrite
        source: "/*"
        destination: "/index.html"
